# Generated by Django 5.1.3 on 2024-11-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='user',
        ),
    ]
