# Generated by Django 5.1.3 on 2024-11-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bulkemailtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
